### ISSUE TITLE
unable to compile on mac with mono 3.2

### ISSUE THREAD

**Issue by colombounplug** [zenogantner/MyMediaLite#443]
Errors:

/zenogantner-MyMediaLite-ac30d22/src/MyMediaLite-nogui.sln (default targets) ->
(Build target) ->
/zenogantner-MyMediaLite-ac30d22/src/Tests/Tests.csproj (default targets) ->
/usr/local/Cellar/mono/3.2.8/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

	Correlation/BinaryCosineTest.cs(85,22): error CS0012: The type `System.Collections.Generic.ISet`1<T>' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

	 8 Warning(s)
	 1 Error(s)

Time Elapsed 00:00:05.4303200
make[1]: *** [all] Error 1
make: *** [mymedialite] Error 2

It would be great if someone can provide a solution for this.

**Comment by zenogantner** [comment]
Mono is now at version 4.2. Can you try it with a newer mono?
